      SUBROUTINE OMGJ6                                                  
C                                                                       
C     INCLUDE                                  ( DATE: 15 AUGUST 1997 ) 
C     
      INCLUDE  'DSHARE'                                                 
C                                                                       
C                                                                       
      DELP=0.0
	DELP=(FLOAT(INT(DELP*1000000.0)))/1000000.0                                                          
      RETURN                                                            
      END                                                               
